In [2]:
import pandas as pd
NewtargetFile = "/Volumes/时伟SSD512G/扶贫数据-11列-英文推文筛选.xlsx"

In [3]:
df = pd.read_excel(NewtargetFile) #读取excel文件

In [13]:
df.head

<bound method NDFrame.head of         Unnamed: 0        date      time         username place  \
0                0  2021-10-06  07:44:40  donotforget_911   NaN
1                1  2021-10-06  06:57:11          noalgos   NaN
2                2  2021-10-06  06:38:58    openparachute   NaN
3                3  2021-10-06  06:16:10       ertemnuneg   NaN
4                4  2021-10-06  05:48:25  jasonralston101   NaN
...            ...         ...       ...              ...   ...
723309      872503  2020-10-15  10:53:40        alokpatel   NaN
723310      872504  2020-10-15  10:28:26  politicsbitcoin   NaN
723311      872505  2020-10-15  10:22:54  chenche31178573   NaN
723312      872508  2020-10-15  08:02:49        zeesweeet   NaN
723313      872509  2020-10-15  07:12:35    article10echr   NaN

                                                    tweet language  \
0       The Biden administration is warning China over...       en
1       @Stalingrad_Poor @DebraG_Robins driven by Chin...       en
2       @ouuooo @sajidjavid Perhaps your reading is pr...       en
3       Coordination among "so-called allies" against ...       en
4       It’s not about being black, white, Hispanic, J...       en
...                                                   ...      ...
723309  @LloydMathias @CounterPointTR @BGRIndia @NewsM...       en
723310  You know the economists of the world have fuck...       en
723311  @JoeBiden President Biden, you have full suppo...       en
723312  @ViennaRosee My heart is breaking, the CCP mak...       en
723313  @lilbarbxers The author of that article makes ...       en

                                                 mentions  replies_count  \
0                                                      []              0
1                                                      []              0
2                                                      []              0
3       [{'screen_name': 'ipacglobal', 'name': 'inter-...              1
4                                                      []              0
...                                                   ...            ...
723309                                                 []              0
723310                                                 []              1
723311                                                 []              0
723312                                                 []              1
723313                                                 []              0

        retweets_count  likes_count hashtags
0                    0            0       []
1                    1            1       []
2                    0            0       []
3                    0            0       []
4                    0            0       []
...                ...          ...      ...
723309               0            0       []
723310               0            0       []
723311               0            0       []
723312               0            2       []
723313               0            0       []

[723314 rows x 12 columns]>

In [14]:
df_daterank = df.sort_values('date', ascending = True) #按日期排序

In [15]:
df_daterank.head()

,Unnamed: 0,date,time,username,place,tweet,language,mentions,replies_count,retweets_count,likes_count,hashtags
566386,650558,2007-01-26,20:21:14,philcampbell,NaN,Really was considering going to the chang thai...,en,[],0,0,0,[]
566385,650557,2007-03-26,10:05:21,aardling,NaN,Electric guitar music? Rhino cavalry? Chinese ...,en,[],0,0,0,[]
238045,275563,2007-04-01,07:09:58,maushopgirl,NaN,watching the evening news - glutten from china...,en,[],0,0,0,[]
651696,749619,2007-04-09,12:04:13,cdt,NaN,China cautiously enlists NGO help in poverty f...,en,[],0,0,0,[]
566384,650556,2007-04-13,07:56:47,boogenstein,NaN,"@andrewbarnett We have an average Thai, a poor...",en,[],0,0,0,[]

In [16]:
#筛选出想要的日期范围2013-01-01到2021-12-31，赋给新的DataFrame：df_daterank_datefliter
df_daterank_datefliter = df_daterank[(df_daterank['date'] >= '2013-01-01') & 
                                        (df_daterank['date'] <= '2021-12-31')]

In [18]:
df_daterank_datefliter = df_daterank_datefliter.drop(columns = ['Unnamed: 0'])
#reset_index()重置索引 https://www.jianshu.com/p/223de3248f90
#在获得新的index，原来的index变成数据列，保留在数据框中，不想保留原来的index的话可以使用参数drop=True，默认False。
df_daterank_datefliter = df_daterank_datefliter.reset_index(drop = True)
df_daterank_datefliter.head()

,date,time,username,place,tweet,language,mentions,replies_count,retweets_count,likes_count,hashtags
0,2013-01-01,14:25:30,chinese_bagelco,NaN,"@kathygriffin poor richard lewis: 13 yrs old, ...",en,[],0,0,0,[]
1,2013-01-01,16:50:21,dmercedes_,NaN,Poor Chinese people they can't even celebrate ...,en,[],0,0,0,['sucksforyou']
2,2013-01-01,17:44:50,ashleighelle,NaN,Poor Chinese girl last night got her up to dan...,en,[],0,0,1,[]
3,2013-01-01,19:00:15,rennocchio,NaN,I think the only Chinese Amber knows to say is...,en,[],0,0,0,[]
4,2013-01-01,19:06:17,rotipeeta,NaN,"@kurohera awww poor bb~ if it's any help, ther...",en,[],0,0,0,[]

In [19]:
df_daterank_datefliter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 639167 entries, 0 to 639166
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   date            639167 non-null  object
 1   time            639167 non-null  object
 2   username        639167 non-null  object
 3   place           3608 non-null    object
 4   tweet           639167 non-null  object
 5   language        639167 non-null  object
 6   mentions        639167 non-null  object
 7   replies_count   639167 non-null  int64
 8   retweets_count  639167 non-null  int64
 9   likes_count     639167 non-null  int64
 10  hashtags        639167 non-null  object
dtypes: int64(3), object(8)
memory usage: 53.6+ MB

In [25]:
#df_keywords = df_daterank_datefliter[df_daterank_datefliter['tweet'].str.contains('relief|alleviation|mitigation|anti|against|aid|aids|aiding|aided|help|helped|helping|helps|ease|eased|easing|eases|relieve|alleviate|mitigate|alleviated|relieved|mitigated|relieving|relieves|alleviates|alleviating|mitigates|mitigating|reduce|reducing|reduced|reduces|reduction|decrease|decreasing|decreased|decreases|support|supporting|supported|supports|sustain|sustains|sustaining|sustained|bear|bore|born|bearing|bears|stand|stood|stands|standing|suffer|suffered|suffering|suffers|hold|held|holding|holds|experience|experienced|experiences|experiencing|undergo|undergoing|undergone|undergoes|underwent|withstand|withstanding|withstands|withstood|endure|endures|endured|enduring', 
                                                                    #na = False, case = False)]
#根据关键词筛选与扶贫相关的文本
#df_keywords = df_daterank_datefliter[df_daterank_datefliter['tweet'].str.contains('relief|alleviation|mitigation|anti|against|aid|aids|aiding|aided|help|helped|helping|helps|ease|eased|easing|eases|relieve|alleviate|mitigate|alleviated|relieved|mitigated|relieving|relieves|alleviates|alleviating|mitigates|mitigating|reduce|reducing|reduced|reduces|reduction|decrease|decreasing|decreased|decreases|support|supporting|supported|supports|sustain|sustains|sustaining|sustained|assist|assisting|assists|assisted|assistance|confront|confronting|confrontation|confronted|confronts|counter|counters|countering|countered|combat|combats|combated|combating|eliminate|eliminated|eliminates|eliminating|elimination|fight|fights|fighting|fought|eradicate|eradicates|eradicating|eradicated|eradication|finish|finished|finishing|finishes|end|edning|ends|ended|lift|lifts|lifting|lifted|battle|battles|declare victory|declared victory|declaring victory|declares victory|shake|shook|shaken|shakes|shaking|remove|removing|removed|removes|removel|get|gets|getting|got|gotten|rid|ridding|rids|ridded|solve|solved|solving|solves|solution|break|breaking|breaks|broke|broken|resolve|resolved|resolving|resolves|settle|settled|settles|settling|settlement|over|overcome|overcoming|overcomes|overcame|win|wins|winning|won|conquer|conquering|conquered|conquers|surmount|surmounts|surmounting|surmounted|put|putting|puts|fulfil|fulfilment|fulfiling|fulfiled|fulfils|complete|completes|completed|completing|complement|complements|complementing|complemented|accomplish|accomplishes|accomplished|accomplishing|accomplishment|success|succeed|succeeds|succeeding|succeeded|off|out|up|subsidize|subsidizes|subsidized|subsidizing|subsidization|subsidisation|subsidy|subsidies|allowance|allowances|battled|battling|never|hope|effort|efforts|urge|urged|urging|urges|hope|hopes|hoped|hoping|maintain|maintaining|maintains|maintained|progress|progresses|progressing|progressed|encourage|encouraged|encourages|encouraging', 
                                                                                  #na = False, case = False)]  

df_keywords = df_daterank_datefliter[df_daterank_datefliter['tweet'].str.contains('relief|alleviation|mitigation|anti|aid|aids|aiding|aided|help|helped|helping|helps|ease|eased|easing|eases|relieve|alleviate|mitigate|alleviated|relieved|mitigated|relieving|relieves|alleviates|alleviating|mitigates|mitigating|reduce|reducing|reduced|reduces|reduction|support|supporting|supported|supports|assist|assisting|assists|assisted|assistance|eliminate|eliminated|eliminates|eliminating|elimination|fight|fights|fighting|fought|eradicate|eradicates|eradicating|eradicated|eradication|finish|finished|finishing|finishes|end|edning|ends|ended|lift|lifts|lifting|lifted|battle|battles|declare victory|declared victory|declaring victory|declares victory|shake|shook|shaken|shakes|shaking|remove|removing|removed|removes|removel|rid|ridding|rids|ridded|solve|solved|solving|solves|solution|break|breaking|breaks|broke|broken|resolve|resolved|resolving|resolves|settle|settled|settles|settling|settlement|overcome|overcoming|overcomes|overcame|win|wins|winning|won|success|succeed|succeeds|succeeding|succeeded|subsidize|subsidizes|subsidized|subsidizing|subsidization|subsidisation|subsidy|subsidies|allowance|allowances|battled|battling|finish|finished|finishing|finishes|conquer|conquering|conquered|conquers|beat|beaten|beats|beating', 
                                                                                  na = False, case = False)] 

#df_keywords = df_daterank_datefliter[df_daterank_datefliter['tweet'].str.contains('relief|alleviation', na = False, case = False)] 
df_keywords

,date,time,username,place,tweet,language,mentions,replies_count,retweets_count,likes_count,hashtags
4,2013-01-01,19:06:17,rotipeeta,NaN,"@kurohera awww poor bb~ if it's any help, ther...",en,[],0,0,0,[]
7,2013-01-01,23:13:13,waltydunlop,NaN,I'm afraid the only thing I thought as I saw a...,en,[],0,0,0,[]
22,2013-01-01,05:13:11,mrjintheuk,NaN,Battle damage is clear. Tonight was a massive ...,en,[],0,0,0,[]
30,2013-01-01,01:29:28,financenewscast,NaN,"China's economy ends 2012 on a high, but 200m ...",en,[],0,0,0,[]
32,2013-01-01,05:21:28,warr1979,NaN,Welcome 2 another rescission da government kno...,en,[],0,0,0,[]
...,...,...,...,...,...,...,...,...,...,...,...
639160,2021-12-31,13:58:29,ozzey_h,NaN,@wyldeAF @chenweihua @ScottAdamsSays Can guara...,en,[],0,0,0,[]
639162,2021-12-31,17:25:30,redand51ue,NaN,Shedding a crocodile tear for Chinese people f...,en,[],0,0,0,"['ccp', 'emperorxi', 'ccp', 'commonprosperity']"
639163,2021-12-31,20:06:07,ray44758650,NaN,@CGTNOfficial WRONG!! Deng wisely took the CCP...,en,[],0,0,0,[]
639164,2021-12-31,21:52:54,chineseemb_uga,NaN,Here are some excerpts of🇨🇳President Xi Jinpin...,en,[],1,2,9,[]
639166,2021-12-31,11:50:00,xismoments,NaN,"President XiJinping declared ""complete victory...",en,[],3,12,42,['xijinping']

In [26]:
df_keywords = df_keywords.drop(columns = ['language'])
df_keywords = df_keywords.reset_index(drop = True)
df_keywords
#df_keywords.to_excel('/Volumes/时伟SSD512G/扶贫数据-11列-英文推文筛选.xlsx')

,date,time,username,place,tweet,mentions,replies_count,retweets_count,likes_count,hashtags
0,2013-01-01,19:06:17,rotipeeta,NaN,"@kurohera awww poor bb~ if it's any help, ther...",[],0,0,0,[]
1,2013-01-01,23:13:13,waltydunlop,NaN,I'm afraid the only thing I thought as I saw a...,[],0,0,0,[]
2,2013-01-01,05:13:11,mrjintheuk,NaN,Battle damage is clear. Tonight was a massive ...,[],0,0,0,[]
3,2013-01-01,01:29:28,financenewscast,NaN,"China's economy ends 2012 on a high, but 200m ...",[],0,0,0,[]
4,2013-01-01,05:21:28,warr1979,NaN,Welcome 2 another rescission da government kno...,[],0,0,0,[]
...,...,...,...,...,...,...,...,...,...,...
253262,2021-12-31,13:58:29,ozzey_h,NaN,@wyldeAF @chenweihua @ScottAdamsSays Can guara...,[],0,0,0,[]
253263,2021-12-31,17:25:30,redand51ue,NaN,Shedding a crocodile tear for Chinese people f...,[],0,0,0,"['ccp', 'emperorxi', 'ccp', 'commonprosperity']"
253264,2021-12-31,20:06:07,ray44758650,NaN,@CGTNOfficial WRONG!! Deng wisely took the CCP...,[],0,0,0,[]
253265,2021-12-31,21:52:54,chineseemb_uga,NaN,Here are some excerpts of🇨🇳President Xi Jinpin...,[],1,2,9,[]
253266,2021-12-31,11:50:00,xismoments,NaN,"President XiJinping declared ""complete victory...",[],3,12,42,['xijinping']

In [27]:
df_keywords.to_excel('/Volumes/时伟SSD512G/0717扶贫数据-10列-英文-已筛选关键词235267.xlsx')